[project]
name = "polars_dataset"
version = "1.0.0"
description = "Extension of the polars DataFrame with methods for interpolation with the `splines` cargo."
requires-python = ">=3.10"
authors = [{ name = "Mattias Matthiesen" }]
dependencies = [
    "bs4>=0.0.2",
    "polars>=1.17.0",
    "polars_splines>=0.1.2",
]

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"
