[project]
name = "polars-complex"
version = "0.1.0"
description = "Utility functions for working with complex numbers in Polars"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "Mattias Matthiesen" }]
requires-python = ">=3.10"
dependencies = [
    "polars>=1.9.0",
]

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"
